import { BodyContainer } from "@/styles/style";
import AdminAccess from "./admin-access";
import BreadCrumbs from "@/components/BreadCrumbs";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <BreadCrumbs />
      <AdminAccess>{children}</AdminAccess>
    </>
  );
}
