import { BodyContainer } from "@/styles/style";
import AdminAccess from "./admin-access";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <BodyContainer>
      <AdminAccess>{children}</AdminAccess>
    </BodyContainer>
  );
}
